In [24]:
import numpy as np
l1=[20,30,40,50]
l1

[20, 30, 40, 50]

In [33]:
t1=(24,34,44,54)
t1

(24, 34, 44, 54)

In [26]:
#creating a numpy array using np.array
#convewrsion of tuple and list into array
x=np.array(l1)
print(x)
y=np.array(t1)
print(y)


[20 30 40 50]
[24 34 44 54]


In [31]:
#to show the type
print(type(l1))
print(type(t1))

<class 'list'>
<class 'tuple'>


In [12]:
l= ['1.0','2.0','3.0']
a= array(l)
print(a)
print(a.shape)
print(a.dtype)

['1.0' '2.0' '3.0']
(3,)
<U3


In [34]:
#operators in numpy
a = np.array([1, 2, 5, 3]) 
# add 1 to every element 
print (a+1) 
  
# subtract 3 from each element 
print (a-3) 
  
# multiply each element by 10 
print (a*10) 
  
# square each element 
print (a**2) 

# divide each element
print(a/2)
  
# modify existing array 
a *= 2
print ("Doubled each element of original array:", a) 
  
# transpose of array 
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]]) 
  
print ("\nOriginal array:\n", a) 
print ("Transpose of the array",a.T) 

  

[2 3 6 4]
[-2 -1  2  0]
[10 20 50 30]
[ 1  4 25  9]
[0.5 1.  2.5 1.5]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of the array [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [6]:
# datatype of array
d=np.array([1.1,2.0,3.2])
d.dtype

dtype('float64')

In [38]:
e=np.array([96,46,56])
e.dtype

dtype('int32')

In [44]:
l= np.array([1.0,2.0,3.0])
l.dtype

dtype('float64')

In [45]:
# shape of array
l= ['1.0','2.0','3.0']
a= array(l)
print(a)
print(a.shape)

['1.0' '2.0' '3.0']
(3,)


In [47]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
a.shape


(3, 3)

In [56]:
# Indexing and slicing
a=np.array([(91,62,39),(34,59,66),(80,70,60)])
print(a)
# to print first row 
print(a[0])
# to print second row
print(a[1])
print(a[2,2])  # a[1][2] element.
# to print third column
print(a[:,2])

[[91 62 39]
 [34 59 66]
 [80 70 60]]
[91 62 39]
[34 59 66]
60
[39 66 60]


In [57]:
# Numpy flatten()
a=np.array([(1,2,3),(4,5,6)])
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [60]:
# Numpy statistical functions.

#Creating an array of random numbers.
a=np.random.normal(5,0.5,10)
print(a)


[5.49868911 4.97619578 4.76138661 4.17114227 5.30341408 5.76375141
 4.90770536 4.987291   5.1021186  5.6818365 ]


In [68]:
# Standard deviation of items of array
a=np.array([(91,62,39),(34,59,66),(80,70,60)])
np.std(a) 

16.898389140848767

In [63]:
#Minimum item of array.
a=np.array([(91,62,39),(34,59,66),(80,70,60)])
np.min(a)

34

In [66]:
#maximum item of array.
a=np.array([(91,62,39),(34,59,66),(80,70,60)])
np.max(a)

91

In [69]:
# Median of the items of the array.
a=np.array([(91,62,39),(34,59,66),(80,70,60)])
np.median(a)

62.0

In [70]:
# Mean of the items of the array.
a=np.array([(91,62,39),(34,59,66),(80,70,60)])
np.mean(a)

62.333333333333336

In [73]:
# Numpy hstack()
a=np.array([10,20,30,40]) 
b=np.array([50,60,70,80])
np.hstack((a,b))

array([10, 20, 30, 40, 50, 60, 70, 80])

In [74]:
a=np.array([10,20,30,40]) 
b=np.array([50,60,70,80])
np.hstack((b,a))

array([50, 60, 70, 80, 10, 20, 30, 40])

In [75]:
# Numpy vstack()
np.vstack((a,b))


array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [76]:
np.vstack((a,a))


array([[10, 20, 30, 40],
       [10, 20, 30, 40]])

In [77]:
np.vstack((b,b))


array([[50, 60, 70, 80],
       [50, 60, 70, 80]])

In [78]:
np.vstack((b,a))

array([[50, 60, 70, 80],
       [10, 20, 30, 40]])